apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 061709796715.dkr.ecr.us-east-1.amazonaws.com/mybookstore-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50055
