apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bookstore
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Subredes públicas
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-083387554e8c0f31b,subnet-0bf1c655251be83a4"
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
