apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: bookstore
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
    - name: grpc
      port: 50054
      targetPort: 50054
